### ISSUE TITLE
Change captcha for chinese signups

### ISSUE THREAD

**Issue by jnordberg** [steemit/faucet#109]
We need to support signups from China, the GFW blocks the google captcha we use. Our options are: 

1. Switch captcha provider (yinxiangma.com was suggested)
2. Skip the captcha for ip addresses originating from China
3. Roll our own solution (using something like [svg-captcha](https://github.com/lemonce/svg-captcha))

Both 2. and 3. are gamble by an determined attacker (chinese vpn, train ann on easily generated dataset).

I'm in favour of 3. since it provides some level of protection and we will not be relying on a third party. 

cc @bonustrack @sneak @goldibex

**Comment by sneak** [comment]
Agree with @goldibex - use a China-appropriate CAPTCHA for Chinese IPs.

**Comment by jnordberg** [comment]
Ok, sounds good. I'll break this up in to two issues so we can get the ball rolling on Chinese signups.
