### ISSUE TITLE
Add Chinese captcha provider for Chinese IPs

### ISSUE THREAD

**Issue by jnordberg** [steemit/faucet#121]
Possible provider: http://www.yinxiangma.com (bad omen them not serving their site over https...)

Anyone know of other captcha solutions that work in China?

Blocked by #120 
Refs #109

**Comment by gregory-latinier** [comment]
Binance is using this : http://www.geetest.com/
It looks like a piece of puzzle that you need to move to the correct place using a slider. It requires a user action but it's pretty fast.

**Comment by bonustrack** [comment]
We going to use geetest.com as suggested by @gregory-latinier. Would that work for you @jnordberg?

**Comment by jnordberg** [comment]
Sounds good (they also don't have a https version of their website, industry standard in china? 😆)

**Comment by jnordberg** [comment]
Found this: https://github.com/GeeTeam/gt-node-sdk (lock the version down with = and make sure the npm package tarball contains the same code as the git repo if you end up using it)

**Comment by gregory-latinier** [comment]
This is the old version
https://github.com/GeeTeam/gt3-node-sdk is the package referenced in npm
