### ISSUE TITLE
Prevent creation of names similar to known steem services like exchanges

### ISSUE THREAD

**Issue by dnotestein** [steemit/faucet#130]
On the blocktrade's steem account creator, we block the creation of names similar to the names of existing services such as bittrex, poloniex, blocktrades, etc (e.g bitttrex, bloktrades). It'd be nice if the steemit faucet did the same: it might discourage casual creation of such names if there was a cost associated with their creation.

**Comment by gregory-latinier** [comment]
Would you care to share the blacklisted accounts ?
@bonustrack what do you think ? Should we implement such an algorithm ?

**Comment by jnordberg** [comment]
This is a good suggestion, we should add it to gatekeeper. I'll create an issue over there. @dnotestein if you're willing to share your list of names that would be great

**Comment by dnotestein** [comment]
alpha	 
bittrex
blocktrades
changelly
coinpayments.net	 
freewallet	 
freewallet.org
hitbtc	 
livecoin.net	 
minnowbooster	 
openledger
openledger-dex	 
poloniex
rudex
shapeshift.io
steemthat
buildawhale
