### ISSUE TITLE
Switch to async handlers

### ISSUE THREAD

**Issue by jnordberg** [steemit/faucet#143]
Currently all api handlers are async and wrapped in try/catch, a better solution would be to create an async wrapper that returns unexpected errors as 500 or using something like https://github.com/spatools/express-async-router

Refs #135

**Comment by gregory-latinier** [comment]
What if we do this 
```
const accounts = await steem.api.getAccountsAsync([req.query.username]).catch((err) => {
    console.log('/check_username', 'steem.api.getAccountsAsync', err);
    error = 'error_api_general';
  });
```

instead of

```
try {
    const accounts = await steem.api.getAccountsAsync([req.query.username]);
    if (accounts && accounts.length > 0 && accounts.find(a => a.name === username)) {
      error = 'error_api_username_used';
    }
  } catch (err) {
    console.log('/check_username', 'steem.api.getAccountsAsync', err);
    error = 'error_api_general';
  }
```

does this work for you ?

**Comment by jnordberg** [comment]
Why is that better than having promise-capable request handlers?

**Comment by gregory-latinier** [comment]
Here we can still send a specific error message. I've set a general message because of the lack of specifications.
But if you just want a general error handler I'll look into a wrapper

**Comment by jnordberg** [comment]
To pass along messages just tag the errors you throw and check for them in the error handler. E.g.

```js
// route handler
const error = new Error('Ooops')
error.api_msg = 'some_msg_tag'
error.http_code = 418
throw error

// error handler
response.writeHead(error.http_code || 500)
response.end(error.api_msg || 'Internal error')
```

Bonus points if you create a Error subclass for the purpose and check it with instanceof :)
