### ISSUE TITLE
link to create account in email is wrong

### ISSUE THREAD

**Issue by bnchdrff** [steemit/faucet#154]
https://github.com/steemit/faucet/blob/master/routes/api.js#L261

https://github.com/steemit/faucet/blob/master/routes/api.js#L419

link should be `create_account` not `create-account`

**Comment by bonustrack** [comment]
It's 2 differents routes, the user receive an email with a link to the page `/create-account` to complete his signup flow and there is another route `/api/create_account` not visible for the user used for the faucet API to create an account.
