### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by jnordberg** [steemit/faucet#157]
Was able to create an account without verifying email address, is this intentional? Phone verification was required and worked

**Comment by bonustrack** [comment]
Yes its intentional @jnordberg. Email confirmation on step 1 been removed as Jeffrey suggested. If the email is wrong the user will not receive the precious link to create his account. The user email is confirmed in step 2 when user click on the link he receive by mail.

**Comment by jnordberg** [comment]
Ok thanks @bonustrack. That makes sense, closing this
