### ISSUE TITLE
Conveyor calls fail with Invalid signature

### ISSUE THREAD

**Issue by bonustrack** [steemit/faucet#163]
Call to conveyor are not working anymore since 3 days are breaking the steps in signup flow. Is something changed? We are using `salut` in localhost actually + `https://conveyor.steemitdev.com` . Here is error from steem-js:
```RPCError: Unauthorized: Verification failed (Invalid signature)```

**Comment by jnordberg** [comment]
We have setup a admin account for dev now, I'll get you the keys to that
