### ISSUE TITLE
Set user status as 'pending_creation' while account creating

### ISSUE THREAD

**Issue by bonustrack** [steemit/faucet#164]
To avoid concurrent requests to `api/create_account` we should set user status as `pending_creation` in the database in the begin of the request. We should return an error if the user send a request and has already a status of `pending_creation`. If the account creation failed we can set the user back to `approved` status so he can start the account creation process again.

Related to #155

**Comment by bnchdrff** [comment]
reference implementation:

set a unique creation hash for this user's session as early as possible during the account creation call:
https://github.com/steemit/condenser/blob/master/src/server/api/general.js#L137-L147

later on, just before making the call to create the account, ensure there are no other pending account creation calls for this user:
https://github.com/steemit/condenser/blob/master/src/server/api/general.js#L182-L195

unset the creation hash if account creation fails so the user can try again:
https://github.com/steemit/condenser/blob/master/src/server/api/general.js#L210
