### ISSUE TITLE
Generated password format

### ISSUE THREAD

**Issue by jnordberg** [steemit/faucet#178]
Faucets generated passwords does not follow the `P5` prefixed "master password" convention condenser has.

This is bad since we use that to detect if users accidentally post their passwords and save them from shooting themselves in the foot

CC @sneak @goldibex @bonustrack

**Comment by goldibex** [comment]
`P5` implies a Base58Check-encoded 33-byte private key. What do faucet-generated passwords look like, or rather, how are they generated? @jnordberg @sneak

**Comment by jnordberg** [comment]
This is a faucet generated password: `H62qRVgU1CuGpAohrxYngwywuJBjkGiv`

**Comment by jnordberg** [comment]
Generated here maybe: https://github.com/steemit/faucet/blob/b04906dcad09f5aef21bb423e675b63319bdd596/src/utils/auth.js

**Comment by goldibex** [comment]
there's absolutely no reason for this code to exist. eliminate it wherever used and replace it with `keyUtils.get_random_key().toWif()`. problem solved.

**Comment by sneak** [comment]
Hold on.  I, too, disagree with this code - but we don't want a WIF.  The password is *not* a WIF and it shouldn't look like a WIF.  The password is hashed, with the username and role name, in the world's lamest KDF, to create the role's key.  All of the WIFs for the various roles in the normal case are derived from the password.  The password is generated (lamely) by taking a WIF and prefixing it with `P` - the person who designed it thought this was a good way to be able to generate a random string that could be checked for correct entry.

We should replace it.  But we should do so deliberately, and not with something that looks like a WIF, which this unsalted, high-entropy password *is not*.

**Comment by jnordberg** [comment]
Agreed, but we should keep backwards compatibility until we deliberately change it.

**Comment by sneak** [comment]
Yes, generate a random WIF and prefix it with a `P` to match what condenser is doing today.  We will forklift it another day.

**Comment by jnordberg** [comment]
Yep, that's what we did in #179

**Comment by sneak** [comment]
ahh ok carry on then; I misread @goldibex comment as requesting we not use the `P` static prefix
