### ISSUE TITLE
Faucet account name validation strings don't mention periods as accepted characters

### ISSUE THREAD

**Issue by plink01001** [steemit/faucet#190]
In the faucet locales script, it says: _Account name should contain only letters, digits, and dashes_. Periods are allowed as well. Is excluding periods done on purpose or a limitation of the faucet application, or is it just missing information from the string?

https://github.com/steemit/faucet/blob/e6c62c9d62ed20be5290377cece4258ad29cf084/src/locales/en.json#L65

**Comment by gregory-latinier** [comment]
It's just missing information AFAIK
