### ISSUE TITLE
Phone number verification

### ISSUE THREAD

**Issue by jnordberg** [steemit/faucet#195]
We have both false positives and false negatives in our local validator. We should remove the local validator and just do a basic check that it looks like a phone number, then let the twillo do the validation for us. They return code `21614` or `21211` for invalid numbers.

**Comment by mvandeberg** [comment]
Related: steemit/steem#2106

**Comment by tusharbjobs** [comment]
Hello, is this resolved?

I still get the same error for the Indian number which is a valid 10-digit number and working to date.

Thought of checking since this seems to be a very old issue.
