### ISSUE TITLE
Change account creation fee to 0.1 STEEM

### ISSUE THREAD

**Issue by bonustrack** [steemit/faucet#196]
Currently new account created are paid `0.5 STEEM`. It seem we can lower it down to `0.1 STEEM` if we higher a bit the delegation amount. Changing this would save lot of STEEM.

**Comment by jnordberg** [comment]
Should we implement dynamic delegation calculations? We could use dsteem [createAccount](https://jnordberg.github.io/dsteem/classes/broadcastapi.html#createaccount) which would calculate the lowest possible fee and delegation amount possible when creating.

At the time of writing the lowest possible values are: 
```
CREATE_ACCOUNT_FEE="0.100 STEEM"
CREATE_ACCOUNT_DELEGATION="29650.022515 VESTS"
```

**Comment by roadscape** [comment]
Currently Steemit target delegation is 15 SP (less creation fee); if we were to implement dynamic calcs, perhaps use `max(min_create_delegation, target_delegation)`?

**Comment by jnordberg** [comment]
Makes sense, here's a snippet that does exactly that:

https://playground.steem.vc/#590a2596bf499a0e8e612405c23b7191

Gives me a delegation of `30671.691058 VESTS`

**Comment by roadscape** [comment]
@jnordberg I think it might need a small adjustment:

```
      const delegation = Asset.max(
          minDelegation.subtract(sharePrice.convert(creationFee.multiply(ratio))),
-         targetDelegation,
+         targetDelegation.subtract(sharePrice.convert(creationFee)),
      )
```

The numbers I get are `Asset.max(29644.93363618, 30462.7249089022)`

**Comment by jredbeard** [comment]
This has been updated - I used 30690 VESTS and 0.1 STEEM, this is just slightly above 15 SP, I verified accounts are being created properly with the new values.
