### ISSUE TITLE
Clarify phone number format

### ISSUE THREAD

**Issue by TimCliff** [steemit/faucet#197]
When a new user is entering their phone number, it tells them it is an invalid number if they enter it in the form of `XXX-XXX-XXXX`. `XXXXXXXXXX` is valid though. It should make it clear to the user what format(s) are accepted so they enter the data correctly.

Invalid:
![image](https://user-images.githubusercontent.com/20735105/36083491-9148210c-0f78-11e8-9b09-2b5b297c25c4.png)

Valid:
![image](https://user-images.githubusercontent.com/20735105/36083493-94f626b4-0f78-11e8-934d-780a0164b63a.png)

**Comment by jnordberg** [comment]
Validator should remove any non-digit character when run, also the country code if entered in the number input should be removed along with changing the dropdown to the correct value.
