### ISSUE TITLE
User reported issue - entering wrong email cannot be fixed

### ISSUE THREAD

**Issue by TimCliff** [steemit/faucet#205]
A user reported this issue from steemit.chat help. I'm not sure if anything can be done to the signup flow in order to handle this, but I can see multiple users running into it.

_I typed the wrong e-mail address during registration. I want to change but I do not accept that the phone number is registered .. What should I do to improve?_

**Comment by gregory-latinier** [comment]
The only way to allow a user to use his phone again is to say that a phone number is considered as used only when the account has been created in the blockchain but that would allow multiple accounts creation with the same phone.

If think the best way to handle this would be to use the update user infos feature on faucet admin to set the new email and add a functionality to resend the email to continue the creation flow.
Would that be OK for you @jnordberg ?

**Comment by TimCliff** [comment]
This will be addressed by #220
