### ISSUE TITLE
Pending account approval since 6 weeks

### ISSUE THREAD

**Issue by paplooo** [steemit/faucet#209]
Hello there devs, let me first tell you that how great it is to build a community like steemit rewarding the users for their contributions, I can't wait to start contributing. However, there are some hiccups for me to get started. 
I have already verified my email and phone, it's been over 5 weeks and I haven't received an approval email.  
![image](https://user-images.githubusercontent.com/2665554/36162504-f2dacde2-10e6-11e8-8155-8a466a55c0a1.png)
 I have tried everything under the sun to get help with this issue. 
After signing up I waited for about 2 weeks before getting in touch with a mod on chat in the #help channel. After that I filled up a stuck sign up form, waited for another 2 weeks and still nothing. So, I got in touch with the mods again and I was given the option to create an account through other methods.

Any help to get the signup approved will be really appreciated. 

Thanks in advance!

**Comment by jnordberg** [comment]
I understand your frustration, we are working really hard to improve the signup systems to make the experience better for everyone. However this issue tracker is not for support so I'm closing this.

**Comment by krischik** [comment]
One year later and the account of a friend is stuck as well. HF20 didn't make account opening any more reliable.
