### ISSUE TITLE
User Reported Issue - SMS not received, then phone number in use

### ISSUE THREAD

**Issue by TimCliff** [steemit/faucet#214]
Several users are reporting that as they are going through the signup process, they do not get the SMS message to their phone right away (some have said it shows up an hour or sometimes even a day later). When they go back and try again though, it says their phone number is in use, even though they have not successfully verified an account with their phone number yet.

**Comment by gregory-latinier** [comment]
I don't see how their phone could be used as this flag is set to true only when they input the right code.
But there is actually another issue. If the user leaves this page without typing the code when he comes back a new one will be set.
We should send back the same code when the user comes back or ask for a resend.

**Comment by jnordberg** [comment]
Agreed that that sounds strange, @TimCliff could you ask them for exact steps to reproduce?

@gregory-latinier why is generating a new code a problem?

**Comment by gregory-latinier** [comment]
If the user comes back because the generated code took too long to receive, if we regenerate a new one that also takes too long, that will be an endless loop.

**Comment by jnordberg** [comment]
Ok, gotcha, I guess it does not hurt to resend the same code since we are limiting the number of retries globally. But we are fixing the symptom here and not the cause, messages should not take more than a couple of minutes to arrive at most.

**Comment by gregory-latinier** [comment]
We can only control when the message is sent which is right away. It's up to Twilio to deliver it.

**Comment by jnordberg** [comment]
That's not correct. Twilio has delivery callbacks and send timeouts we can utilise but hopefully we don't have to resort to that with the switch to copilot in #213

**Comment by TimCliff** [comment]
I've tried and have been unable to reproduce this. I'll leave it open for a few days in case anyone new has a report of the issue to get more specific steps, otherwise I'll close it.

**Comment by TimCliff** [comment]
There have been no new reports of this.
