### ISSUE TITLE
User Reported Issue - Phone number entry is removing initial "0" for Australian number

### ISSUE THREAD

**Issue by TimCliff** [steemit/faucet#234]
A user has a phone number in the format +61(043)XXX-XXXX

When they enter it, it accepts it as a valid phone number:
![image](https://user-images.githubusercontent.com/20735105/36624721-af7c1174-18d8-11e8-8d0d-fe0647ca5583.png)

When it sends the validation though, it doesn't include the "0" in the "043":
![image](https://user-images.githubusercontent.com/20735105/36624731-d2e74840-18d8-11e8-88df-75e940f1d4d7.png)

This is causing the SMS to fail to be delivered.

**Comment by goldibex** [comment]
- [ ] Timebox research (1 hr) on behavior of leading zeroes in international phone numbers
- [ ] Strip the leading zero if there's a zero

**Comment by gl2748** [comment]
Twilio uses E.164 formatting. In this case, the number input by the user is converted to E.164 format, which makes it appear to be incorrect.

For example: a national phone (GB in this case) that has a leading 0 number `07740 125622`  is converted to `+447740125622`.

To the average user seeing a number sent to this E.164 number might appear to be incorrect.

Using Twilio's phone number validator however reveals it to be correct:
https://www.twilio.com/lookup:
```
{
    "country_code": "GB",
    "phone_number": "+447740125622",
    "national_format": "07740 125622",
    "url": "https://lookups.twilio.com/v1/PhoneNumber/+447740125622",
}
```

The next step is to consider how we are converting user numbers:

In our case the input is a mixture of the country code  and the number in the national format.
this is then passed to an instance of google's  [libphonenumber](https://github.com/googlei18n/libphonenumber) 

It is here that we might have an issue [`INTERNATIONAL`](https://github.com/steemit/faucet/blob/6ab364f1e2272ec9792334c008d55da7903e72b1/routes/api.js#L235) is passed as the Phone Number Format (should be `E164` as this is Twilio's preferred format), this would remove the necessity of this [RegExp](https://github.com/steemit/faucet/blob/6ab364f1e2272ec9792334c008d55da7903e72b1/routes/api.js#L237) that removes spaces from the phone number... themselves required by the `INTERNATIONAL` formatter and not by `E164`

If this was done, we would be doing no other re-formatting of the phone number, leaving that entirely up to Google's library. At this point we would be reasonably confident that any issue with phone number formatting was not on us...

Finally we could add one more step to protect against further issues. In the examples provided by google there is a check available `isValidNumber()`  that  the user input number ought to pass before it is passed to the formatter.

Altogether this would look like:
```js
let phoneNumber = phoneUtil.parse(req.body.phoneNumber, countryCode)
const isValid = phoneUtil.isValidNumber(phoneNumber)
  if (!isValid) {
    throw new ApiError({ cause, field: 'phoneNumber', type: 'error_phone_invalid' });
  }
  try {
    phoneNumber = phoneUtil.format(
      phoneNumber,
      PNF.E164,
    );
  } catch (cause) {
    throw new ApiError({ cause, field: 'phoneNumber', type: 'error_phone_format' });
  }

```

**Comment by gl2748** [comment]
closed by pr:https://github.com/steemit/faucet/pull/252
