### ISSUE TITLE
Setup faucet funnel tracking

### ISSUE THREAD

**Issue by jnordberg** [steemit/faucet#241]
Most of the plumbing to send the events to overseer is in place already, what is missing is a reference id per user that persists throughout the signup steps.

The reference id should be assignable by querystring when initiating signup so that the funnel can include steps prior to signup

**Comment by jnordberg** [comment]
Needs https://github.com/steemit/steempunks/issues/251

**Comment by gl2748** [comment]
Refs: #188

**Comment by jnordberg** [comment]
This is now blocked by #313
