### ISSUE TITLE
Include paid sign up options

### ISSUE THREAD

**Issue by bnchdrff** [steemit/faucet#245]
moved from https://github.com/steemit/condenser/issues/2568

As a user, I want to sign up for a Steem account instantly. 

-----

Let's provide options on signup.steemit.com for users to be able to signup instantly via paid options, including Blocktrades and AnonSteem. 

- [x] Add links to Blocktrades and AnonSteem's relevant "pay-for" signups

**Comment by bnchdrff** [comment]
see https://github.com/steemit/faucet/pull/236

**Comment by pkattera** [comment]
Here are some designs which build on @netuoso work in his PR #236 – you may be able to use his PR as a starting point for these changes. Feedback welcome on the approach and text using within these designs. 

### For the first page of signup

![artboard](https://user-images.githubusercontent.com/1121139/37722270-cb8ee070-2ce8-11e8-9620-558f47c90e3a.jpg)

**Text**

> **Sign up options**
> 
> [Steemit] is not a typical social app. It's powered by the Steem blockchain, run by community members all around the world. To protect the system against bots and name squatters, a small fee is required to create an account. 
> 
> We're happy to cover this fee for you. However, we'll need your email and phone number to manually check that you're a real person. This process could take 1-2 weeks.
> 
> If you'd prefer to stay anonymous or skip the queue, pay the account creation fee and sign up from a third party service.

Note: References to 'Steemit' should use a variable which allows us to replace it with friendly third party apps like Busy, if they come via a URL like `signup.steemit.com?ref=busy`

### Lightbox interaction if the user chooses 'Pay for sign up'

![signup2](https://user-images.githubusercontent.com/1121139/37720641-ef0375c4-2ce4-11e8-8561-d023f8499b2f.jpg)

**Lightbox text**

This text was mainly taken from the FAQs

> **Blocktrades** https://blocktrades.us/create-steem-account
> 
> A third-party tool that accepts Bitcoin, Ethereum, Litecoin, STEEM and more. Blocktrades charges it's own small fee.
> 
> **AnonSteem** https://anon.steem.network/
> 
> A third-party tool that accepts Bitcoin, Litecoin and STEEM. AnonSteem also charges it's own a small fee.
> 
> **SteemConnect** https://steemit.com/news/@timcliff/new-tool-from-busy-org-create-new-steem-blockchain-accounts-with-steemconnect
> 
> Try this option if you already have a Steem account and want to pay to set up a new account for yourself or a friend.


### If the user hits the 'Sign up for free' button, they are taken to Username step (previously the first step of signup)

![signup3](https://user-images.githubusercontent.com/1121139/37720647-f2b2254e-2ce4-11e8-9f13-156573061e3e.jpg)

Here is SVG file displayed on the right hand side (with back up PNGs if required):

[new-image-for-username-step.zip](https://github.com/steemit/faucet/files/1834055/new-image-for-username-step.zip)

Note: We'll need to add a 'Go back' link under the 'Continue' button for this step.

**Comment by TimCliff** [comment]
@pkattera this looks great!

A few suggestions:
- Wording update: _If you'd like to skip the queue or stay anonymous, you can pay the account creation fee using a third party service._
- I'm pretty sure `bitcoin` is lower case when referred to as a currency.
- Include SteemCreate (also in the FAQ) which allows users to pay using a credit card.
- For both BlockTrades and AnonSteem, update wording to: _it's own small fee for using their service._
- SteemConnect: Add _There is no additional fee for using the SteemConnect service._
- Update wording to: _Note: Steemit, Inc. is not affiliated with these services, and does not receive any money from paid accounts._ (You may even need to use stronger wording to prevent any form of official enforcement, similar to the FAQ disclaimer. Something to check on.)
- Also, is it possible to hit the URL without a `?ref` link? If so, what happens then?

**Comment by pkattera** [comment]
@TimCliff I agree with all your suggestions. But instead of `bitcoin`, I'm just going to use their currency codes, e.g. BTC, LTC etc, since it's it previously wasn't consistently applied with SBD.

Here are the updated screens, a some additional copy tweaks.

### Sign up for Steemit

![steemit-signup](https://user-images.githubusercontent.com/1121139/37752708-9b256eb8-2d56-11e8-83fa-5bd9a7bf7d7b.jpg)

Text:

> [Steemit] is not a typical social app. It's powered by the Steem blockchain and run by community members all around the world. To help protect them against bots and name squatters, a small fee is charged to create new accounts.
> 
> We're happy to cover this fee for you but we'll need your email and phone number to manually check that you're a real person. This process could take 1-2 weeks.
> 
> If you'd like to skip the queue or stay anonymous, you can pay the account creation fee using a third party service.

### Pay for sign up

![third-parties](https://user-images.githubusercontent.com/1121139/37751789-91abb608-2d51-11e8-8155-8455a63cd607.jpg)

Text:

> **Blocktrades** https://blocktrades.us/create-steem-account
> 
> A third-party tool that accepts BTC, ETH, LTC, STEEM and more. Blocktrades charges it's own small fee for using their service.
> 
> **AnonSteem** https://anon.steem.network/
> 
> A third-party tool that accepts BTC, LTC and STEEM. AnonSteem also charges it's own small fee for using their service.
> 
> **SteemCreate** https://www.steemcreate.com/
> 
> A third-party tool that accepts credit cards or BTC. SteemCreate also charges it's own small fee for using their service.
> 
> **SteemConnect** https://steemit.com/news/@timcliff/new-tool-from-busy-org-create-new-steem-blockchain-accounts-with-steemconnect
> 
> Try this option if you already have a Steem account and want to pay to set up a new account for yourself or a friend. There is no additional fee for using the SteemConnect service

### If the sign up is not attached to any app (e.g. a pure Steem blockchain account)

Currently signup.steemit.com defaults to Steemit signups. We should design for the state when the faucet lives somewhere like connect.steem.com. So if no app is attached to the signup, the text on the first page should read:

> **Sign up options**
>  
> The Steem blockchain powers many real time content apps like Steemit, and is run by community members all around the world. To help protect them against bots and name squatters, a small fee is charged to create new accounts.
> 
> We're happy to cover this fee for you but we'll need your email and phone number to manually check that you're a real person. This process could take 1-2 weeks.
> 
> If you'd like to skip the queue or stay anonymous, you can pay the account creation fee using a third party service.

**Comment by gl2748** [comment]
We want to make sure we are keeping track of state, for these user modals, (e.g. also #232). I think there is an additional task here to improve state mgmt in faucet.

**Comment by sneak** [comment]
Let's not say "1-2 week queue" in the copy.  The queue should be cleared every 24-48h.  If anyone's waiting 2 weeks, something's broken.

**Comment by TimCliff** [comment]
From a UX perspective, it should probably be the “worst case” that can be close to guaranteed. If it is normally 24-48 hours, but once and a while may take up to a week - then “one week” would be better. If it says accounts are approved within 48 hours, but there is a case where it takes longer - there will be a flood of support issues from users that think something went wrong.

**Comment by cyon1c** [comment]
@TimCliff agreed. Until we really have this process ironed out, it seems better to take an underpromise, overdeliver approach, rather than the reverse.

**Comment by sneak** [comment]
Why promise any time window?  Publishing a huge waiting time is discouraging when a user should in practice only be waiting a day or two.

**Comment by TimCliff** [comment]
With the current signup process, one of the number one issues that we get reported in the help channel is _”I just applied for my account a few hours (or a day) ago, and it still hasn’t been approved yet. What went wrong?”_ Some clarity on what users should expect would help a lot with that portion of the UX.

**Comment by sneak** [comment]
For that small number of users. For the rest of the users, telling them “it may take weeks” when it normally takes days degrades the UX. 

Our goal should not necessarily be minimizing support requests, but building the best experience for the greatest number of users.
