### ISSUE TITLE
Invalid token error after 7 days

### ISSUE THREAD

**Issue by TimCliff** [steemit/faucet#246]
There are a small handful of users who are receiving a link in their email that generates an "Invalid Token" error. More details will be provided over a private channel.

![image](https://user-images.githubusercontent.com/20735105/37074938-e157b8fa-2194-11e8-8438-1702f199ef1d.png)

**Comment by TimCliff** [comment]
Five new instances of this have been reported

**Comment by TimCliff** [comment]
@gl2748 @pkattera @gregory-latinier not sure if you are aware of this issue. We are getting about 5-10 of these per day in steem.chat #help.

**Comment by pkattera** [comment]
Any ideas on what is causing it?

**Comment by TimCliff** [comment]
No idea. Something related to character encoding was one possibility - but just a guess. I will supply all of the details I have privately.

**Comment by gregory-latinier** [comment]
The token sent by email after the approval has a validity of 7 days 
https://github.com/steemit/faucet/blob/master/routes/api.js#L334
After 7 days the error invalid token will be thrown.

If the user doesn't create an account before that the process is completely broken and he has no means to continue. His email and phone number will be marked as used too.
Even if that doesn't solve the bug this is bad design.

**Comment by bonustrack** [comment]
@TimCliff is the 7 days expiration explain the reason why users having this issue? Some users having this issue before 7 days?

**Comment by TimCliff** [comment]
@bonustrack I know at least some of the users affected didn’t act on their email within the seven days. I don’t have enough info from the current reports to know how many were because of this though. The only information I collected (other than what the users volunteered when describing their issue) was their email address and signup link.

**Comment by TimCliff** [comment]
@bonustrack 100% of the reported instances of this since you asked me to check have all been over 7 days old. I think it is safe to say https://github.com/steemit/faucet/pull/253 will fix it going forward.

**Comment by lgendrot** [comment]
What is the recourse for users who have already experienced this issue?

**Comment by agerhbour** [comment]
I'm also now in this category. Got the email, didn't have a chance to sign up when I first saw it. Only just remembered to try but I'm two days too late.

**Comment by urspine** [comment]
I am facing the same problem.

**Comment by pkattera** [comment]
@urspine @agerhbour We have a new ticket #259 to resend a new approval email to people affected by this issue

**Comment by sherryclark** [comment]
I am withing the 7 days. When I click on the verification link I got in my email I get this error. 

![screenshot 2018-03-26 at 11 07 49 pm](https://user-images.githubusercontent.com/37822649/37944848-47fa203c-314b-11e8-95d9-421e1767bddd.png)

 
If I hit continue it goes the a page where it says to enter my phone number but all it says is invalid token. This is super frustrating.

**Comment by TimCliff** [comment]
Please ask for help in the help channel of steem chat.
