### ISSUE TITLE
receive  error_api_token_invalid when confirming email

### ISSUE THREAD

**Issue by sherryclark** [steemit/faucet#268]
I am withing the 7 days. When I click on the verification link I got in my email I get this error.If I hit continue 

![screenshot 2018-03-26 at 11 07 49 pm](https://user-images.githubusercontent.com/37822649/37945014-253562f4-314c-11e8-9025-ffcbc40252c8.png)

it goes the a page where it says to enter my phone number but all it says is invalid token. This is super frustrating.
--

**Comment by TimCliff** [comment]
This is a duplicate issue. Please ask for help in the help channel of steem chat.

**Comment by sherryclark** [comment]
I figured it out. I had accidentally opened two windows from that link. Thanks!
