### ISSUE TITLE
verify email cannot lead to dead-end

### ISSUE THREAD

**Issue by roadscape** [steemit/faucet#275]
Confusing UX; clicking a link in a faucet email must provide more information or lead to next step.

Audit current flow and ensure links always lead to:

1. if phone not verified -> verify phone page
2. if not yet approved -> basic details about status
3. if not yet created -> account creation page

![image](https://user-images.githubusercontent.com/5168676/38209157-13a2efca-3679-11e8-88f6-8078d1e33a97.png)

**Comment by pkattera** [comment]
Also, in case the user has somehow provided all of the information, please some additional text telling them, we'll notify them when they're approved. This covers the following case:

> A person who was perhaps in a 'stuck' state with a pending email validation, who was sent the new validation link, clicked it, and because their phone number was already validated there is no further action for them to take.

Example:

![screen shot 2018-04-02 at 11 08 05 pm](https://user-images.githubusercontent.com/1121139/38232217-ee1bc8d8-36ca-11e8-8c89-2fafe1f5b394.png)

New additional text:

> You've now provided all the information required. We manually review applications to protect against bots and spam. Due to a high volume of sign ups, this process may take 1–3 weeks. We'll email you as soon as you're approved.

**Comment by gl2748** [comment]
https://github.com/steemit/faucet/blob/fab9194c9b13e27059413682e194a9f1645a12b3/src/components/ConfirmEmail.js#L94
