### ISSUE TITLE
Reminder email for approved users prior to faucet

### ISSUE THREAD

**Issue by pkattera** [steemit/faucet#278]
– Requires copy
– Log who the email is sent to in Conveyor
– Unsubscribe option

**Comment by gl2748** [comment]
refs #277

**Comment by jnordberg** [comment]
https://github.com/steemit/steempunks/blob/master/hacks/1johan/conveyor-migration/migrate.js

**Comment by gl2748** [comment]
We want to record this in overseer somehow. And also keep track of who from this cohort completes / does not complete.

**Comment by bnchdrff** [comment]
see steemit/steempunks#299

**Comment by bnchdrff** [comment]
see https://github.com/steemit/faucet/commit/e65b75861347ea355d3c979d1eea1bccfa2cc645 also
