### ISSUE TITLE
[admin] Allow admins to change state of already rejected/approved signups

### ISSUE THREAD

**Issue by jnordberg** [steemit/faucet#294]
In the case of a misclick or re classification admins need the ability to change the state of an already approved or rejected user.

The admin ui should allow this this option with a "Are you really really sure?" dialog and the admin endpoint needs to be updated to allow this state transition.

We also need to make sure that when a user transitions from approved -> rejected and clicks their old approval email link that case is handled gracefully

**Comment by pkattera** [comment]
An admin can change from rejected to approved anytime.
Only allow change of status from approved to rejected if the user hasn't created their account.

**Comment by pkattera** [comment]
Include a page for rejected users
