### ISSUE TITLE
Ref is not working.

### ISSUE THREAD

**Issue by gl2748** [steemit/faucet#328]
When i navigate to signup.steemit.com from a site such as busy.org I expect to see the referrer's logo / branding present on the signup first step.

![screenshot from 2018-04-29 09-35-13](https://user-images.githubusercontent.com/3374538/39407750-af511858-4b90-11e8-9746-0b26cc83b086.png)

**Comment by bonustrack** [comment]
@pkattera Yes it was working previously, using `?ref=busy` should remove the Steemit logo.

**Comment by gl2748** [comment]
Need to check that ref is saved in db.
