### ISSUE TITLE
log new signup actions

### ISSUE THREAD

**Issue by bnchdrff** [steemit/faucet#331]
previously we'd log `signup_start` only if the visitor landed on the page & the step is `username` -- this isn't the case anymore though, since #327 

see https://github.com/steemit/faucet/blob/master/src/components/Signup.js#L96

we should track clicks on either of the two free/paid signup buttons, and also actions taken after that (outbound link clicks, closing modal & clicking free option button)

**Comment by gl2748** [comment]
Refs https://github.com/steemit/overseer/issues/18
