### ISSUE TITLE
Update Faucet admin README instructions, for local dev.

### ISSUE THREAD

**Issue by gl2748** [steemit/faucet#337]
Also remove `faucet-admin` .envs

**Comment by jnordberg** [comment]
What's wrong with `admin/README.md`? Aslo I'm not seeing any faucet-admin .env file

**Comment by gl2748** [comment]
Complete command to start faucet admin from `/admin` would be:
```
env $(tr "\\n" " " < ../.env) REACT_APP_SERVER_ADDRESS="http://localhost:3001/admin" REACT_APP_GOOGLE_CLIENT_ID="XXX" PORT=3000 yarn start
```
The admin README states:
```
REACT_APP_SERVER_ADDRESS="http://localhost:3001/admin" yarn start
```
The example .env should be updated to cover all new .envs

**Comment by gl2748** [comment]
Without **[this env var](https://github.com/steemit/faucet/blob/master/admin/public/index.html#L8)** being set I cannot get the faucet admin to work locally:

The instructions don't describe how to reliably start the faucet-admin.

Perhaps the instructions in the faucet admin Readme can be updated  to:
```
REACT_APP_SERVER_ADDRESS="http://localhost:3001/admin" REACT_APP_GOOGLE_CLIENT_ID="xxxkeygoesherexxx" PORT=3000 yarn start
```
In the alternative  we could rename `REACT_APP_GOOGLE_CLIENT_ID`
to: `GOOGLE_CLIENT_ID` and then the following would also work:
```
env $(tr "\\n" " " < ../.env) REACT_APP_SERVER_ADDRESS="http://localhost:3001/admin"  PORT=3000 yarn start
```

**Comment by jnordberg** [comment]
That env var is not being used anymore, it could be removed. `GOOGLE_CLIENT_ID` is served to the client over the api. The instructions in the admin README are up to date. What's the problem you're having with getting the admin to work locally?
