### ISSUE TITLE
TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by Pecking** [steemit/faucet#357]
![image](https://user-images.githubusercontent.com/27414779/40400237-d8b55f60-5e73-11e8-8e36-f16f0ad9e831.png)

How should I configure it?

**Comment by gl2748** [comment]
@Pecking please make sure your .env vars are configured correctly. This looks like this one in particular is missing or mal-configured:
https://github.com/steemit/faucet/blob/master/.env.example#L2
