### ISSUE TITLE
Phone code verification problems on steemit 

### ISSUE THREAD

**Issue by Anilnishadd** [steemit/faucet#377]
I was trying to sign up steemit and during the process I did not get the phone verification code on the same day, I got it on the next day. Well that's not an issue! The issue is, I tried to continue the sign up process through the e-mail confirmation link and the problem is after entering the phone no. the page doesn't continue to the code verification page at all. I tried pressing the "continue" several times and it did not load at all ..  !it is stuck . what do i do please help me out

**Comment by TimCliff** [comment]
Currently, you will need to start over with a new signup attempt, using a different email address and username.
