### ISSUE TITLE
create_account_operation deprecation

### ISSUE THREAD

**Issue by youkaicountry** [steemit/faucet#387]
In HF20, `create_account_operation` is deprecated in favor of `create_claimed_account_operation`.

Accounts are now created by spending account credits. Account credits are gained via the new `claim_account_operation`. A STEEM fee can be paid to gain credits, or if 0 fee is passed, then resource credits are consumed to generate the credit.

For the faucet, `claim_account_operation` should be called with 0 fee continuously on some schedule to generate a cache of account credits. If there are not enough RC left to generate an account credit, it will simple not generate one.

**Additional notes:**
The number of account credits is `pending_claimed_accounts` in `account_object`.

The same account should be used for the two operations.

The script should probably have a config value for the minimum RC level, it should, on its own, stop doing `claim_account_operation` when RC drops below that level.

The faucet account has to be "hot" -- the machine with its keys needs to be online to handle user requests as they come in.

The bigger the faucet's SP balance is, the faster it regenerates RC, and the more accounts it can claim.

**Comment by mac128k** [comment]
Closed as part of SD-104.
